/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'journal-transaction': RouteRecordInfo<'journal-transaction', '/Journal-transaction', Record<never, never>, Record<never, never>>,
    'list-cartes': RouteRecordInfo<'list-cartes', '/list-cartes', Record<never, never>, Record<never, never>>,
    'list-client': RouteRecordInfo<'list-client', '/list-client', Record<never, never>, Record<never, never>>,
    'list-lignes&arrets': RouteRecordInfo<'list-lignes&arrets', '/list-lignes&arrets', Record<never, never>, Record<never, never>>,
    'list-terminaux': RouteRecordInfo<'list-terminaux', '/list-terminaux', Record<never, never>, Record<never, never>>,
    'list-transactions': RouteRecordInfo<'list-transactions', '/list-transactions', Record<never, never>, Record<never, never>>,
    'list-vehicule': RouteRecordInfo<'list-vehicule', '/list-vehicule', Record<never, never>, Record<never, never>>,
    'liste-users': RouteRecordInfo<'liste-users', '/liste-users', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
